### ISSUE TITLE
Image download does not seem to work anymore

### ISSUE THREAD

**Issue by cratoo** [bropat/ioBroker.eufy-security#191]
Since an iobroker restart, the adapter does not seem to be able to download an image from the cloud.
```
2021-11-17 10:27:23.868  - error: eufy-security.0 (626) Status return code not 200 [{"status":204,"statusText":"No Content"}]
2021-11-17 10:27:23.870  - error: eufy-security.0 (626) unhandled promise rejection: Cannot convert undefined or null to object
2021-11-17 10:27:23.871  - error: eufy-security.0 (626) TypeError: Cannot convert undefined or null to object
    at Station.startDownload (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:2060:20)
```

Also the offline-image states are not updated anymore.

I'm currently still running 0.7.0 in case this matters. I'm still in the need to update js-controller, thus not being able to upgrade the admin, which is why I can't go to 0.7.2.
But the status code seems to tell me, that the download really is not working and does not point to a version problem.

**Comment by cratoo** [comment]
`2021-11-17 12:15:44.959  - info: eufy-security.0 (1362) Retry get image in 5 seconds from url: https://security-app-eu.eufylife.com/v1/s/g/XXXXXX (retry_count: 1 error: Not Found message: Not Found)...`
Apparently this is a timing issue again :( This also explains why sometimes the image works.

**Comment by xanthos84** [comment]
got the same error....

**Comment by harryslapalot** [comment]
Same issue here. I updated to 0.7.2 before but the issue seems to be unrelated to the update.
Is there a quick fix to disable image download completely?

**Comment by Sascha-U** [comment]
Same here I get the same error <html>
eufy-security.0 | 2021-11-19 13:12:20.549 | error | Status return code not 200 [{"status":204,"statusText":"No Content"}]
-- | -- | -- | --

Data points for last event are all empty

**Comment by bropat** [comment]
The following error has been fixed in version 0.7.3:

```
Status return code not 200 [{"status":204,"statusText":"No Content"}]
```

**Comment by cratoo** [comment]
@bropat can we reopen this issue? Yes the 204 messages are gone, but I still don't have updates for the images. As @Sascha-U mentioned, the last_event states stay empty.
Here a debug log, but apparently there is no error message in it. But the link to the image works, so from my point of view, the adapter potentially needs to do more retries?
```
2021-11-27 10:06:20.722  - debug: eufy-security.0 (19699) [PushNotificationService.onMessage] Normalized push message received 
[{"name":"Doorbell","event_time":1638003978110,"type":7,"station_sn":"T8010PXXX","device_sn":"T8210PXXX","title":"","content":"Doorbell:Someone has been spotted","push_time":1638003980660,"channel":0,"cipher":42,"event_session":"20211127_100618","event_type":3102,"file_path":"/media/XXXX/Camera00/h265_20211127100614.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/XXXX","push_count":2,"notification_style":3}]
2021-11-27 10:06:20.725  - debug: eufy-security.0 (19699) [EufySecurity.onPushMessage] Received push message [{"name":"Doorbell","event_time":1638003978110,"type":7,"station_sn":"T8010PXXX","device_sn":"T8210PXXX","title":"","content":"Doorbell:Someone has been spotted","push_time":1638003980660,"channel":0,"cipher":42,"event_session":"20211127_100618","event_type":3102,"file_path":"/media/XXXX/Camera00/h265_20211127100614.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/XXXXXXXX","push_count":2,"notification_style":3}]
2021-11-27 10:06:35.805  - debug: eufy-security.0 (19699) [EufySecurity.onStateChange] state eufy-security.0.XXX.cameras.XXXX.person_detected changed: false (ack = true) was already acknowledged, ignore it...
2021-11-27 10:06:35.864  - debug: eufy-security.0 (19699) [EufySecurity.onDevicePropertyChanged] onDevicePropertyChanged(): Property "personName" not implemented in this adapter (device: XXXXX value: {"value":"","timestamp":1638003995727})
```

**Comment by bropat** [comment]
@cratoo 

Can you please open a separate issue?

In order to understand exactly where the problem lies, I would ask you to reproduce the problem and then send me the debug logs.
